### ISSUE TITLE
Gnome 46 issue

### ISSUE THREAD

**Issue by Neo2SHYAlien** [JordanViknar/Noiseclapper#12]
Hello thank you for you work. I have issue with gnome 46. First Gnome report it as outdated, if I disable version validation I got this stack trace
The settings of extension Noiseclapper@JordanViknar had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:187:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:207:19
start@resource:///org/gnome/gjs/modules/script/package.js:191:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I'm using Debian Sid with Gnome 46 with latest code base of the extension
![image](https://github.com/JordanViknar/Noiseclapper-GNOME/assets/1681317/aa98d52c-e6de-426e-9721-935521c37f13)

**Comment by JordanViknar** [comment]
> Hello thank you for you work. I have issue with gnome 46. First Gnome report it as outdated, if I disable version validation I got this stack trace The settings of extension Noiseclapper@JordanViknar had an error:
> 
> ```
> SyntaxError: import declarations may only appear at top level of a module
> ```
> 
> Stack trace:
> 
> ```
> _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
> ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
> OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
> async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
> _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:187:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
> run@resource:///org/gnome/gjs/modules/script/package.js:207:19
> start@resource:///org/gnome/gjs/modules/script/package.js:191:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```
> 
> I'm using Debian Sid with Gnome 46 with latest code base of the extension ![image](https://private-user-images.githubusercontent.com/1681317/317645808-aa98d52c-e6de-426e-9721-935521c37f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDI0NTcsIm5iZiI6MTcxMjA0MjE1NywicGF0aCI6Ii8xNjgxMzE3LzMxNzY0NTgwOC1hYTk4ZDUyYy1lNmRlLTQyNmUtOTcyMS05MzU1MjFjMzdmMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDcxNTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI3YmUzMmYyMTFjNWViMWJkODI5YTIyNjNkYmE0NGRlZDEyN2U1ZDI4NzUyZTAyZDVmMzM1MDY0Y2U2OGJkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VkEfK9XyhKe4nV1VBdiZ_8tkxEGuYWpL24U2X-LvvOg)

Sorry for the big delay in response, I hadn't received a notification for your issue for some reason.

> First Gnome report it as outdated

I'm aware you already mentioned it, but are you ***sure*** you're using the latest git commit/GitHub Actions package of the extension ? Normally, it enables GNOME 46 support and has some minor code changes to adapt to the new version.

The errors seem quite a bit unexpected to me, I'll admit. Considering [Debian Sid's package is still at 44](https://packages.debian.org/sid/gnome) while you mention being on GNOME 46, are you using some kind of unofficial package ?
If so, it wouldn't be out of the question that it could be installed incorrectly.
Test other extensions, see if they run into the same issues.

**Comment by Neo2SHYAlien** [comment]
You are compactly right!
Some of the components in Sid are version 46 but main components are 44. After switching to 42-44 branch all is fine.
