### ISSUE TITLE
Support for Soundcore Life Q20i

### ISSUE THREAD

**Issue by forabi** [JordanViknar/Noiseclapper#18]
I'd like to add support for this, some guidance on how to get started with the code would be helpful

**Comment by JordanViknar** [comment]
> I'd like to add support for this, some guidance on how to get started with the code would be helpful

It's very simple : the list of supported devices is stored in
`src/common.ts`
Fork the repository and add your device's name in your system's Bluetooth settings to `supportedDeviceNames`.

Then, assuming you want to test it, package the extension and install it using `make install` (you can check the *Makefile* for more details). If the dependencies needed are not installed on your system (and you don't want to install them), you can also try to directly commit to GitHub and install the `Noiseclapper@JordanViknar.zip` file inside the artifact that GitHub Actions automatically produces for each commit.

If testing is successful, add your device to `README.md` as supported, commit your changes to GitHub (if you haven't already done so) and make a pull request to this repository.

(Also, minor comment : write the string element using `'` and not `"`, like with the other lines, so the linter doesn't get upset. It doesn't matter that much, else.)

___

Or, **if you want to directly test on your system without doing any of that**, just go in GNOME's extension folder, go in my extension's folder, and add your device in `supportedDeviceNames` in `common.js`.

Thank you in advance for the contribution. :+1:

**Comment by forabi** [comment]
I've added it to the array, and now it does not complain about no devices being found, but it just does nothing when I switch from e.g. normal to noise-cancelling or vice versa

**Comment by JordanViknar** [comment]
> I've added it to the array, and now it does not complain about no devices being found, but it just does nothing when I switch from e.g. normal to noise-cancelling or vice versa

Just to be certain, there's no error about the Soundcore application being active on your phone either, right ?
Else, the signals the application uses may simply be incompatible with your device.

There was a terminal mode in the past where you could see the output of the Python command the extension relies on, but it got removed when I was looking to simplify the application a while back. If the extension doesn't send an error message of any kind, I assume that command "succeeds" so I'm not sure it'd be of any use anyways.

**Comment by JordanViknar** [comment]
Inactive.
